version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-93t80w19ejiy"
s3_prefix = "test-stack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
