AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  parking-app

Resources:
  
  ParkingLotEntryFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src
      Handler: entry.lambda_entry
      Runtime: python3.8
      Policies:
      - AmazonDynamoDBFullAccess
      Events:
        EntryEvent:
          Type: Api 
          Properties:
            Path: /entry
            Method: post

  ParkingLotExitFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src
      Handler: exit.lambda_exit
      Runtime: python3.8
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        ExitEvent:
          Type: Api
          Properties:
            Path: /exit
            Method: post

  MyParkingTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: parkingLot
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  ParkingLotEntryFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Parking Lot Entry Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/entry/"
  ParkingLotExitFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Parking Lot Exit Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exit/"

